insert into Archive.Book values(1, 'y', 'n', 'fantasy', 'City of Bones', 'Mortal Instruments', 530, 'АСТ');
insert into Archive.Book values(2, 'y', 'n', 'fantasy', 'City of Ashes', 'Mortal Instruments', 517, 'АСТ');
insert into Archive.Book values(3, 'y', 'n', 'fantasy', 'City of Glass', 'Mortal Instruments', 581, 'АСТ');
insert into Archive.Book values(4, 'y', 'n', 'fantasy', 'City of Fallen Angels', 'Mortal Instruments', 480, 'АСТ');
insert into Archive.Book values(5, 'y', 'n', 'fantasy', 'City of Lost Souls', 'Mortal Instruments', 672, 'АСТ');
insert into Archive.Book values(6, 'y', 'n', 'fantasy', 'City of Heavenly Fire( part 1)', 'Mortal Instruments', 482, 'АСТ');
insert into Archive.Book values(7, 'y', 'n', 'fantasy', 'City of Heavenly Fire( part 2)', 'Mortal Instruments', 336, 'АСТ');
insert into Archive.Book values(8, 'y', 'y', 'detectives', 'A Study in Scarlet', 'Sherlock Holmes', 176, 'БИСС Артура Конан Дойла');
insert into Archive.Book values(9, 'y', 'n', 'fantasy', 'Harry Potter and the Sorcerer''s Stone', 'Harry Potter', 352, 'Bloomsbury');
insert into Archive.Book values(10, 'n', 'n', 'novel', 'Jane Eyre', NULL, 512, 'Эксмо');
insert into Archive.Book values(11, 'y', 'n', 'novel, love', 'Me before you', 'Louise Clark', 480, 'Иностранка');
insert into Archive.Book values(12, 'y', 'y', 'fantasy, love', 'Часовой ключ', 'Часодеи', 368, 'Росмэн');
insert into Archive.Book values(13, 'y', 'y', 'fantasy, love', 'Часовое сердце', 'Часодеи', 400, 'Росмэн');
insert into Archive.Book values(14, 'n', 'y', 'novel', 'Ночь после выпуска', NULL, 120, 'Детская литература');

insert into Archive.Author values(1, 'Cassandra', 'Claire', '1973-07-31', 'russian, english');
insert into Archive.Author values(2, 'Artur', 'Conan Doyle', '1859-05-22', 'russian, english');
insert into Archive.Author values(3, 'Joan Kathleen', 'Rowling', '1965-07-31', 'english');
insert into Archive.Author values(4, 'Charlotte', 'Bronte', '1816-04-21', 'english');
insert into Archive.Author values(5, 'Владимир', 'Тендряков', '1923-12-05', 'russian');
insert into Archive.Author values(6, 'Наталья', 'Щерба', '1981-11-16', 'russian');
insert into Archive.Author values(7, 'Jojo', 'Moys', '1969-08-04', 'english');

insert into Archive.Illustrator values(1, 'Natalia', 'Mikhalchuk', 'y', 'Textile and plastic inserts, hard cover, thick paper', 'Watercolor');
insert into Archive.Illustrator values(2, 'Olga', 'Zakis', 'y', 'Bright drawings, hard cover, thick paper', 'Pop art');
insert into Archive.Illustrator values(3, NULL, NULL, 'n', NULL, NULL);
insert into Archive.Illustrator values(4, 'Cassandra', 'Gene', 'y','Gold stamping, thick paper, black and white and color illustrations.', 'Graphic novel');

insert into Archive.Film values(1, 9, 'Harry Potter', '2002-03-21', 'fantasy', 'Daniel Radcliffe, Emma Watson, Rupert Grint');
insert into Archive.Film values(2, 11, 'Me Before You','2016-07-07', 'melodrama', 'Emilia Clark, Charles Dans');
insert into Archive.Film values(3, NULL, 'The Fault In Our Stars','2014-09-4', 'melodrama','Ansel Elgort, Shailene Woodley');

insert into Archive.Shop values(1, 'Labyrinth', 'n', 'г.Долгопрудный, Лихачёвский просп., 64', 'https://www.labirint.ru/books/');
insert into Archive.Shop values(2, 'Ozon', 'n', 'г.Долгопрудный, Лихачёвское ш., 6', 'https://www.ozon.ru/');
insert into Archive.Shop values(3, 'Bookvoed', 'y', NULL, 'https://www.bookvoed.ru/');
insert into Archive.Shop values(4, NULL, NULL, NULL, NULL);

insert into Archive.Reader values(1, 9.8, 'The books are wonderful, read in one breath. At first, I did not want to buy and read a book ... the impressions after the film did not leave positive emotions. But then she decided and remained impressed. I advise you to read to fans of youth fantasy and urban legends.)');
insert into Archive.Reader values(2, 8.7, 'Roman Charlotte Bronte Jane Eyre liked me exclusively. Yes, few expected a review of this book from a man, because, of course, the novel is primarily female, but ... I was always impressed with stories in which the main character is a child who is confronted with real adult problems, even tragedies. Because, in my opinion, it is incredibly interesting to observe how a child’s brain, unspotted by stereotypical ideas about society, makes the most correct decisions based on common sense. It is independent, cheerful, strong.');
insert into Archive.Reader values(3, 4.4, 'This book is required for students of mythology. No, not because Rowling has imbued her creation with a variety of elements of Celtic myths, it is better to study them in primary sources. "Harry Potter" is interesting precisely as the fact of the explosive birth of a new myth - the myth of Harry Potter and Hogwarts. No, these books are good, interesting, but ... not masterpieces in the full sense of the word. And, if the first book on which I am writing this review, at least, is distinguished by a certain originality, then the following parts of the series already suffer from both predictability and monotony, but repeated dose intake is so important for the consumer that the quantity violates quality.');
insert into Archive.Reader values(4, 9.1, 'Oh, this book! Strange heroes, strange behavior. The book makes you cry and laugh, but you should definitely read it to see love in all its stages.');
insert into Archive.Reader values(5, 0.0, NULL);
insert into Archive.Reader values(6, 5.2, 'I have been waiting for this book for a long time. In the library there, in the shops there, I had to buy on the Internet. Did not regret. The plot is interesting, based on the camp and the adventures of children from Eflar on Ostal. I enjoyed reading.');
insert into Archive.Reader values(7, 6.8, 'The final book of the guns of death ... everything is fine ... The only thing that annoyed me about it was the wrong translation of the names, more than once ... Simon is talking to Simon here, and Sebastian just once called them Josslin ... it would be funny if it didn’t hurt the eyes like that .... And in one more scene a solid part was thrown out compared to the original.');
insert into Archive.Reader values(8, 4.8, NULL);
insert into Archive.Reader values(9, 7.3, NULL);
insert into Archive.Reader values(10, 7.9, 'It is a masterpiece. The best series. Every time I re-read, I fully immerse myself in the world of Cassandra Clare. This is a wonderful world. This series has become a part of me and my life. And I still hope that someday they will make a normal film version.');
insert into Archive.Reader values(11, 8.5, 'The book is a worthy continuation of the first parts. Passions and boil in this complex, twilight world. When happiness has become so incredibly close, the emergence of a new threat destroys all hope. This is not Valentine and not undead lower world. ... This is something new, cold and cruel. He is capable of destroying not only the world around him, he will climb into your soul and destroy it from within. And it is through this that the young twilight hunter will have to go to save her lover and the whole world at the same time.');
insert into Archive.Reader values(12, 6.6, 'In general, I liked Astal''s philosophy of watchmaking, gloomy and selfish, Astragor, as an anti-hero and potential enemy, and also touched the next book - Vasilisa’s teaching how to work in the best Eflar school. Curious, dynamic, keep reading.');

insert into Archive.Purchase values(1, 1, 1, 1, 650, 'ABC10-406-ABC');
insert into Archive.Purchase values(2, 2, 1, 10, 544, 'QQG25-201-DAF');
insert into Archive.Purchase values(3, 3, 1, 8, 544, 'BOF10-252-DHF');
insert into Archive.Purchase values(4, 4, 1, 11, 521, 'TAH15-122-NDS');
insert into Archive.Purchase values(5, 5, 1, 9, 650, 'PZD10-798-NLN');
insert into Archive.Purchase values(6, 6, 1, 7, 543, 'ZPY43-172-VKE');
insert into Archive.Purchase values(7, 7, 1, 7, 539, 'VOE47-199-BIB');
insert into Archive.Purchase values(8, 8, 1, 5, 829, 'AAS17-323-SHH');
insert into Archive.Purchase values(9, 9, 2, 3, 809, 'VER94-244-BSK');
insert into Archive.Purchase values(10, 10, 2, 2, 134, 'SONOJS-bDH82');
insert into Archive.Purchase values(11, 11, 3, 4, 325, 'OAOstSRH252h');
insert into Archive.Purchase values(12, 12, 4, 6, 425, NULL);
insert into Archive.Purchase values(13, 12, 4, 6, 425, NULL);
insert into Archive.Purchase values(14, 14, 4, 5, 307, NULL);
insert into Archive.Purchase values(15, 1, 2, 1, 926, 'GSSsjA-aRY15');
insert into Archive.Purchase values(16, 2, 2, 10, 806, 'JREJsn-zeh62');
insert into Archive.Purchase values(17, 1, 3, 1, 563, 'AETHrhae1576a');
insert into Archive.Purchase values(18, 11, 2, 4, 348, 'WGWnnsozg1628j');

insert into Archive.Book_X_Author values(1, 1);
insert into Archive.Book_X_Author values(2, 1);
insert into Archive.Book_X_Author values(3, 1);
insert into Archive.Book_X_Author values(4, 1);
insert into Archive.Book_X_Author values(5, 1);
insert into Archive.Book_X_Author values(6, 1);
insert into Archive.Book_X_Author values(7, 1);
insert into Archive.Book_X_Author values(8, 2);
insert into Archive.Book_X_Author values(9, 3);
insert into Archive.Book_X_Author values(10, 4);
insert into Archive.Book_X_Author values(11, 7);
insert into Archive.Book_X_Author values(12, 6);
insert into Archive.Book_X_Author values(13, 6);
insert into Archive.Book_X_Author values(14, 5);

insert into Archive.Book_X_Illustrator values(1, 4);
insert into Archive.Book_X_Illustrator values(2, 3);
insert into Archive.Book_X_Illustrator values(3, 3);
insert into Archive.Book_X_Illustrator values(4, 3);
insert into Archive.Book_X_Illustrator values(5, 3);
insert into Archive.Book_X_Illustrator values(6, 3);
insert into Archive.Book_X_Illustrator values(7, 3);
insert into Archive.Book_X_Illustrator values(8, 1);
insert into Archive.Book_X_Illustrator values(9, 3);
insert into Archive.Book_X_Illustrator values(10, 3);
insert into Archive.Book_X_Illustrator values(11, 3);
insert into Archive.Book_X_Illustrator values(12, 2);
insert into Archive.Book_X_Illustrator values(13, 2);
insert into Archive.Book_X_Illustrator values(14, 3);

insert into Archive.Book_X_Purchase values(1, 1);
insert into Archive.Book_X_Purchase values(2, 2);
insert into Archive.Book_X_Purchase values(3, 3);
insert into Archive.Book_X_Purchase values(4, 4);
insert into Archive.Book_X_Purchase values(5, 5);
insert into Archive.Book_X_Purchase values(6, 6);
insert into Archive.Book_X_Purchase values(7, 7);
insert into Archive.Book_X_Purchase values(8, 8);
insert into Archive.Book_X_Purchase values(9, 9);
insert into Archive.Book_X_Purchase values(10, 10);
insert into Archive.Book_X_Purchase values(11, 11);
insert into Archive.Book_X_Purchase values(12, 12);
insert into Archive.Book_X_Purchase values(13, 13);
insert into Archive.Book_X_Purchase values(14, 14);
insert into Archive.Book_X_Purchase values(1, 15);
insert into Archive.Book_X_Purchase values(2, 16);
insert into Archive.Book_X_Purchase values(1, 17);
insert into Archive.Book_X_Purchase values(11, 18);
